#!/usr/bin/env python

#-----------------------------------------------------------------------
# language_tools.py
# Author: Ziv Batscha
#-----------------------------------------------------------------------

"""
Dictionary mapping countries to languages spoken. Languages stored as
dictionaries with two keys: 'language' mapping to language name,
'iso' mapping to ISO 639-1 code.

Languages selected by country reflect languages available for
translation by google-cloud-translate api.
"""
country_to_languages = {
    'afghanistan': [{'iso': 'fa', 'language': 'persian'},
                 {'iso': 'ps', 'language': 'pashto'}],
    'albania': [{'iso': 'sq', 'language': 'albanian'}],
    'algeria': [{'iso': 'ar', 'language': 'arabic'}],
    'andorra': [{'iso': 'ca', 'language': 'catalan'}],
    'angola': [{'iso': 'pt', 'language': 'portuguese'}],
    'antigua and barbuda': [{'iso': 'en', 'language': 'english'}],
    'argentina': [{'iso': 'es', 'language': 'spanish'}],
    'armenia': [{'iso': 'hy', 'language': 'armenian'}],
    'australia': [{'iso': 'en', 'language': 'english'}],
    'austria': [{'iso': 'de', 'language': 'german'}],
    'azerbaijan': [{'iso': 'az', 'language': 'azerbaijani'}],
    'bahamas': [{'iso': 'en', 'language': 'english'}],
    'bahrain': [{'iso': 'ar', 'language': 'arabic'}],
    'bangladesh': [{'iso': 'bn', 'language': 'bengali'}],
    'barbados': [{'iso': 'en', 'language': 'english'}],
    'belarus': [{'iso': 'be', 'language': 'belarusian'},
             {'iso': 'ru', 'language': 'russian'}],
    'belgium': [{'iso': 'nl', 'language': 'dutch'}],
    'belize': [{'iso': 'en', 'language': 'english'}],
    'benin': [{'iso': 'fr', 'language': 'french'}],
    'bhutan': [],
    'bolivia': [{'iso': 'es', 'language': 'spanish'}],
    'bosnia and herzegovina': [{'iso': 'bs', 'language': 'bosnian'},
                            {'iso': 'hr', 'language': 'croatian'},
                            {'iso': 'sr', 'language': 'serbian'}],
    'botswana': [{'iso': 'en', 'language': 'english'}],
    'brazil': [{'iso': 'pt', 'language': 'portuguese'}],
    'brunei': [{'iso': 'ms', 'language': 'malay'}],
    'bulgaria': [{'iso': 'bg', 'language': 'bulgarian'}],
    'burkina faso': [{'iso': 'fr', 'language': 'french'}],
    'burundi': [{'iso': 'fr', 'language': 'french'}],
    'cabo verde': [{'iso': 'pt', 'language': 'portuguese'}],
    'cambodia': [{'iso': 'km', 'language': 'khmer'}],
    'cameroon': [{'iso': 'fr', 'language': 'french'},
              {'iso': 'en', 'language': 'english'}],
    'canada': [{'iso': 'fr', 'language': 'french'},
            {'iso': 'en', 'language': 'english'}],
    'central african republic': [{'iso': 'fr', 'language': 'french'}],
    'chad': [{'iso': 'fr', 'language': 'french'},
          {'iso': 'ar', 'language': 'arabic'}],
    'chile': [{'iso': 'es', 'language': 'spanish'}],
    'china': [{'iso': 'zh', 'language': 'chinese (simplified)'}],
    'colombia': [{'iso': 'es', 'language': 'spanish'}],
    'comoros': [{'iso': 'ar', 'language': 'arabic'},
             {'iso': 'fr', 'language': 'french'}],
    'congo': [{'iso': 'fr', 'language': 'french'}],
    'costa rica': [{'iso': 'es', 'language': 'spanish'}],
    "cote d'ivoire": [{'iso': 'fr', 'language': 'french'}],
    'croatia': [{'iso': 'hr', 'language': 'croatian'}],
    'cruise ship': [],
    'cuba': [{'iso': 'es', 'language': 'spanish'}],
    'cyprus': [{'iso': 'el', 'language': 'greek'},
            {'iso': 'tr', 'language': 'turkish'}],
    'czechia': [{'iso': 'cs', 'language': 'czech'}],
    'denmark': [{'iso': 'da', 'language': 'danish'}],
    'djibouti': [{'iso': 'fr', 'language': 'french'},
              {'iso': 'ar', 'language': 'arabic'}],
    'dominica': [{'iso': 'en', 'language': 'english'}],
    'dominican republic': [{'iso': 'es', 'language': 'spanish'}],
    'ecuador': [{'iso': 'es', 'language': 'spanish'}],
    'egypt': [{'iso': 'ar', 'language': 'arabic'}],
    'el salvador': [{'iso': 'es', 'language': 'spanish'}],
    'equatorial guinea': [{'iso': 'es', 'language': 'spanish'},
                       {'iso': 'fr', 'language': 'french'}],
    'eritrea': [{'iso': 'ar', 'language': 'arabic'}],
    'estonia': [{'iso': 'et', 'language': 'estonian'}],
    'eswatini': [],
    'ethiopia': [{'iso': 'am', 'language': 'amharic'}],
    'fiji': [{'iso': 'en', 'language': 'english'},
          {'iso': 'hi', 'language': 'hindi'}],
    'finland': [{'iso': 'fi', 'language': 'finnish'}],
    'france': [{'iso': 'fr', 'language': 'french'}],
    'gabon': [{'iso': 'fr', 'language': 'french'}],
    'gambia': [{'iso': 'en', 'language': 'english'}],
    'georgia': [{'iso': 'ka', 'language': 'georgian'}],
    'germany': [{'iso': 'de', 'language': 'german'}],
    'ghana': [{'iso': 'en', 'language': 'english'}],
    'greece': [{'iso': 'el', 'language': 'greek'}],
    'grenada': [{'iso': 'en', 'language': 'english'}],
    'guatemala': [{'iso': 'es', 'language': 'spanish'}],
    'guinea': [{'iso': 'fr', 'language': 'french'}],
    'guinea-bissau': [{'iso': 'pt', 'language': 'portuguese'}],
    'guyana': [{'iso': 'en', 'language': 'english'}],
    'haiti': [{'iso': 'ht', 'language': 'haitian creole'},
           {'iso': 'fr', 'language': 'french'}],
    'holy see': [{'iso': 'it', 'language': 'italian'},
              {'iso': 'la', 'language': 'latin'}],
    'honduras': [{'iso': 'es', 'language': 'spanish'}],
    'hungary': [{'iso': 'hu', 'language': 'hungarian'}],
    'iceland': [{'iso': 'is', 'language': 'icelandic'}],
    'india': [{'iso': 'hi', 'language': 'hindi'},
           {'iso': 'en', 'language': 'english'},
           {'iso': 'bn', 'language': 'bengali'},
           {'iso': 'gu', 'language': 'gujarati'},
           {'iso': 'ml', 'language': 'malayalam'},
           {'iso': 'mr', 'language': 'marathi'},
           {'iso': 'pa', 'language': 'punjabi'},
           {'iso': 'ta', 'language': 'tamil'},
           {'iso': 'te', 'language': 'telugu'},
           {'iso': 'ur', 'language': 'urdu'},
           {'iso': 'kn', 'language': 'kannada'},
           {'iso': 'sd', 'language': 'sindhi'}],
    'indonesia': [{'iso': 'id', 'language': 'indonesian'}],
    'iran': [{'iso': 'fa', 'language': 'persian'}],
    'iraq': [{'iso': 'ar', 'language': 'arabic'},
          {'iso': 'ku', 'language': 'kurdish (kurmanji)'},
          {'iso': 'hy', 'language': 'armenian'}],
    'ireland': [{'iso': 'en', 'language': 'english'},
             {'iso': 'ga', 'language': 'irish'}],
    'israel': [{'iso': 'iw', 'language': 'hebrew'},
            {'iso': 'ar', 'language': 'arabic'},
            {'iso': 'en', 'language': 'english'}],
    'italy': [{'iso': 'it', 'language': 'italian'}],
    'jamaica': [{'iso': 'en', 'language': 'english'}],
    'japan': [{'iso': 'ja', 'language': 'japanese'}],
    'jordan': [{'iso': 'ar', 'language': 'arabic'}],
    'kazakhstan': [{'iso': 'kk', 'language': 'kazakh'},
                {'iso': 'ru', 'language': 'russian'}],
    'kenya': [{'iso': 'en', 'language': 'english'},
           {'iso': 'sw', 'language': 'swahili'}],
    'kiribati': [{'iso': 'en', 'language': 'english'}],
    'korea, north': [{'iso': 'ko', 'language': 'korean'}],
    'korea, south': [{'iso': 'ko', 'language': 'korean'}],
    'kosovo': [{'iso': 'sq', 'language': 'albanian'},
            {'iso': 'sr', 'language': 'serbian'}],
    'kuwait': [{'iso': 'ar', 'language': 'arabic'}],
    'kyrgyzstan': [{'iso': 'ky', 'language': 'kyrgyz'},
                {'iso': 'ru', 'language': 'russian'}],
    'laos': [{'iso': 'lo', 'language': 'lao'}],
    'latvia': [{'iso': 'lv', 'language': 'latvian'},
            {'iso': 'ru', 'language': 'russian'}],
    'lebanon': [{'iso': 'ar', 'language': 'arabic'}],
    'lesotho': [{'iso': 'en', 'language': 'english'},
             {'iso': 'st', 'language': 'sesotho'}],
    'liberia': [{'iso': 'en', 'language': 'english'}],
    'libya': [{'iso': 'ar', 'language': 'arabic'}],
    'liechtenstein': [{'iso': 'de', 'language': 'german'}],
    'lithuania': [{'iso': 'lt', 'language': 'lithuanian'}],
    'luxembourg': [{'iso': 'lb', 'language': 'luxembourgish'},
                {'iso': 'fr', 'language': 'french'},
                {'iso': 'de', 'language': 'german'}],
    'madagascar': [{'iso': 'mg', 'language': 'malagasy'},
                {'iso': 'fr', 'language': 'french'}],
    'malawi': [{'iso': 'ny', 'language': 'chichewa'}],
    'malaysia': [{'iso': 'ms', 'language': 'malay'}],
    'maldives': [],
    'mali': [{'iso': 'fr', 'language': 'french'}],
    'malta': [{'iso': 'mt', 'language': 'maltese'},
           {'iso': 'en', 'language': 'english'}],
    'marshall islands': [{'iso': 'en', 'language': 'english'}],
    'martinique': [{'iso': 'fr', 'language': 'french'}],
    'mauritania': [{'iso': 'ar', 'language': 'arabic'},
                {'iso': 'fr', 'language': 'french'}],
    'mauritius': [{'iso': 'en', 'language': 'english'},
               {'iso': 'fr', 'language': 'french'}],
    'mexico': [{'iso': 'es', 'language': 'spanish'}],
    'micronesia': [{'iso': 'en', 'language': 'english'}],
    'moldova': [{'iso': 'ro', 'language': 'romanian'}],
    'monaco': [{'iso': 'fr', 'language': 'french'}],
    'mongolia': [{'iso': 'mn', 'language': 'mongolian'}],
    'montenegro': [{'iso': 'sq', 'language': 'albanian'},
                {'iso': 'bs', 'language': 'bosnian'},
                {'iso': 'hr', 'language': 'croatian'},
                {'iso': 'sr', 'language': 'serbian'}],
    'morocco': [{'iso': 'ar', 'language': 'arabic'}],
    'mozambique': [{'iso': 'pt', 'language': 'portuguese'},
                {'iso': 'sw', 'language': 'swahili'}],
    'myanmar': [{'iso': 'my', 'language': 'myanmar (burmese)'}],
    'namibia': [{'iso': 'af', 'language': 'afrikaans'},
             {'iso': 'de', 'language': 'german'},
             {'iso': 'en', 'language': 'english'}],
    'nauru': [],
    'nepal': [{'iso': 'ne', 'language': 'nepali'}],
    'netherlands': [{'iso': 'nl', 'language': 'dutch'},
                 {'iso': 'fy', 'language': 'frisian'}],
    'new zealand': [{'iso': 'en', 'language': 'english'},
                 {'iso': 'mi', 'language': 'maori'}],
    'nicaragua': [{'iso': 'es', 'language': 'spanish'}],
    'niger': [{'iso': 'fr', 'language': 'french'},
           {'iso': 'ha', 'language': 'hausa'}],
    'nigeria': [{'iso': 'en', 'language': 'english'},
             {'iso': 'ha', 'language': 'hausa'},
             {'iso': 'yo', 'language': 'yoruba'},
             {'iso': 'ig', 'language': 'igbo'}],
    'north macedonia': [{'iso': 'mk', 'language': 'macedonian'},
                     {'iso': 'sq', 'language': 'albanian'}],
    'norway': [{'iso': 'no', 'language': 'norwegian'}],
    'oman': [{'iso': 'ar', 'language': 'arabic'}],
    'pakistan': [{'iso': 'pa', 'language': 'punjabi'},
              {'iso': 'ur', 'language': 'urdu'}],
    'palau': [],
    'palestinian state (proposed)': [{'iso': 'ar', 'language': 'arabic'},
                                  {'iso': 'iw', 'language': 'hebrew'},
                                  {'iso': 'en', 'language': 'english'}],
    'panama': [{'iso': 'es', 'language': 'spanish'}],
    'papua new guinea': [{'iso': 'en', 'language': 'english'}],
    'paraguay': [{'iso': 'es', 'language': 'spanish'}],
    'peru': [{'iso': 'es', 'language': 'spanish'}],
    'philippines': [{'iso': 'tl', 'language': 'filipino'},
                 {'iso': 'en', 'language': 'english'}],
    'poland': [{'iso': 'pl', 'language': 'polish'}],
    'portugal': [{'iso': 'pt', 'language': 'portuguese'}],
    'qatar': [{'iso': 'ar', 'language': 'arabic'}],
    'romania': [{'iso': 'ro', 'language': 'romanian'}],
    'russia': [{'iso': 'ru', 'language': 'russian'}],
    'rwanda': [{'iso': 'sw', 'language': 'swahili'},
            {'iso': 'fr', 'language': 'french'},
            {'iso': 'en', 'language': 'english'}],
    'saint lucia': [{'iso': 'en', 'language': 'english'},
                 {'iso': 'fr', 'language': 'french'}],
    'saint vincent and the grenadines': [{'iso': 'en', 'language': 'english'},
                                      {'iso': 'fr', 'language': 'french'}],
    'samoa': [{'iso': 'sm', 'language': 'samoan'},
           {'iso': 'en', 'language': 'english'}],
    'san marino': [{'iso': 'it', 'language': 'italian'}],
    'saudi arabia': [{'iso': 'ar', 'language': 'arabic'}],
    'senegal': [{'iso': 'fr', 'language': 'french'}],
    'serbia': [{'iso': 'sr', 'language': 'serbian'}],
    'seychelles': [{'iso': 'en', 'language': 'english'},
                {'iso': 'fr', 'language': 'french'}],
    'sierra leone': [{'iso': 'en', 'language': 'english'}],
    'singapore': [{'iso': 'zh', 'language': 'chinese (simplified)'},
               {'iso': 'ms', 'language': 'malay'},
               {'iso': 'ta', 'language': 'tamil'},
               {'iso': 'en', 'language': 'english'}],
    'slovakia': [{'iso': 'sk', 'language': 'slovak'}],
    'slovenia': [{'iso': 'sl', 'language': 'slovenian'}],
    'solomon islands': [{'iso': 'en', 'language': 'english'}],
    'somalia': [{'iso': 'so', 'language': 'somali'}],
    'south africa': [{'iso': 'af', 'language': 'afrikaans'},
                  {'iso': 'en', 'language': 'english'},
                  {'iso': 'st', 'language': 'sesotho'},
                  {'iso': 'xh', 'language': 'xhosa'},
                  {'iso': 'zu', 'language': 'zulu'}],
    'south sudan': [{'iso': 'en', 'language': 'english'},
                 {'iso': 'ar', 'language': 'arabic'}],
    'spain': [{'iso': 'eu', 'language': 'basque'},
           {'iso': 'ca', 'language': 'catalan'},
           {'iso': 'gl', 'language': 'galician'},
           {'iso': 'es', 'language': 'spanish'}],
    'sri lanka': [{'iso': 'si', 'language': 'sinhala'},
               {'iso': 'ta', 'language': 'tamil'}],
    'st. kitts and nevis': [{'iso': 'en', 'language': 'english'}],
    'sudan': [{'iso': 'ar', 'language': 'arabic'}],
    'suriname': [{'iso': 'nl', 'language': 'dutch'}],
    'sweden': [{'iso': 'sv', 'language': 'swedish'}],
    'switzerland': [{'iso': 'de', 'language': 'german'},
                 {'iso': 'fr', 'language': 'french'},
                 {'iso': 'it', 'language': 'italian'}],
    'syria': [{'iso': 'ar', 'language': 'arabic'},
           {'iso': 'tr', 'language': 'turkish'},
           {'iso': 'hy', 'language': 'armenian'}],
    'são tomé and príncipe': [{'iso': 'pt', 'language': 'portuguese'}],
    'taiwan': [{'iso': 'zh-TW', 'language': 'chinese (traditional)'}],
    'tajikistan': [{'iso': 'tg', 'language': 'tajik'}],
    'tanzania': [{'iso': 'sw', 'language': 'swahili'},
              {'iso': 'en', 'language': 'english'}],
    'thailand': [{'iso': 'th', 'language': 'thai'}],
    'timor-leste': [{'iso': 'pt', 'language': 'portuguese'}],
    'togo': [{'iso': 'fr', 'language': 'french'}],
    'tonga': [],
    'trinidad and tobago': [{'iso': 'en', 'language': 'english'}],
    'tunisia': [{'iso': 'ar', 'language': 'arabic'},
             {'iso': 'fr', 'language': 'french'}],
    'turkey': [{'iso': 'tr', 'language': 'turkish'}],
    'turkmenistan': [{'iso': 'ru', 'language': 'russian'},
                  {'iso': 'uz', 'language': 'uzbek'}],
    'tuvalu': [{'iso': 'en', 'language': 'english'}],
    'uganda': [{'iso': 'sw', 'language': 'swahili'},
            {'iso': 'en', 'language': 'english'}],
    'ukraine': [{'iso': 'uk', 'language': 'ukrainian'},
             {'iso': 'ru', 'language': 'russian'}],
    'united arab emirates': [{'iso': 'ar', 'language': 'arabic'}],
    'united kingdom': [{'iso': 'en', 'language': 'english'},
                    {'iso': 'cy', 'language': 'welsh'},
                    {'iso': 'gd', 'language': 'scots gaelic'}],
    'uruguay': [{'iso': 'es', 'language': 'spanish'}],
    'us': [{'iso': 'en', 'language': 'english'},
        {'iso': 'es', 'language': 'spanish'}],
    'uzbekistan': [{'iso': 'uz', 'language': 'uzbek'},
                {'iso': 'ru', 'language': 'russian'}],
    'vanuatu': [{'iso': 'en', 'language': 'english'},
             {'iso': 'fr', 'language': 'french'}],
    'venezuela': [{'iso': 'es', 'language': 'spanish'}],
    'vietnam': [{'iso': 'vi', 'language': 'vietnamese'}],
    'western sahara (proposed state)': [{'iso': 'ar', 'language': 'arabic'}],
    'yemen': [{'iso': 'ar', 'language': 'arabic'}],
    'zambia': [{'iso': 'en', 'language': 'english'}],
    'zimbabwe': [{'iso': 'en', 'language': 'english'},
              {'iso': 'sn', 'language': 'shona'},
              {'iso': 'st', 'language': 'sesotho'},
              {'iso': 'xh', 'language': 'xhosa'}]
}

#-----------------------------------------------------------------------

"""
All reported countries at CSSEGISandData/COVID-19.
"""
countries = [
    'afghanistan',
    'albania',
    'algeria',
    'andorra',
    'angola',
    'antigua and barbuda',
    'argentina',
    'armenia',
    'australia',
    'austria',
    'azerbaijan',
    'bahamas',
    'bahrain',
    'bangladesh',
    'barbados',
    'belarus',
    'belgium',
    'benin',
    'bhutan',
    'bolivia',
    'bosnia and herzegovina',
    'brazil',
    'brunei',
    'bulgaria',
    'burkina faso',
    'cabo verde',
    'cambodia',
    'cameroon',
    'canada',
    'central african republic',
    'chad',
    'chile',
    'china',
    'colombia',
    'congo',
    'costa rica',
    "cote d'ivoire",
    'croatia',
    'cruise ship',
    'cuba',
    'cyprus',
    'czechia',
    'denmark',
    'djibouti',
    'dominican republic',
    'ecuador',
    'egypt',
    'el salvador',
    'equatorial guinea',
    'eritrea',
    'estonia',
    'eswatini',
    'ethiopia',
    'fiji',
    'finland',
    'france',
    'gabon',
    'gambia',
    'georgia',
    'germany',
    'ghana',
    'greece',
    'guatemala',
    'guinea',
    'guyana',
    'haiti',
    'holy see',
    'honduras',
    'hungary',
    'iceland',
    'india',
    'indonesia',
    'iran',
    'iraq',
    'ireland',
    'israel',
    'italy',
    'jamaica',
    'japan',
    'jordan',
    'kazakhstan',
    'kenya',
    'korea, south',
    'kuwait',
    'kyrgyzstan',
    'latvia',
    'lebanon',
    'liberia',
    'liechtenstein',
    'lithuania',
    'luxembourg',
    'madagascar',
    'malaysia',
    'maldives',
    'malta',
    'mauritania',
    'mauritius',
    'mexico',
    'moldova',
    'monaco',
    'mongolia',
    'montenegro',
    'morocco',
    'namibia',
    'nepal',
    'netherlands',
    'new zealand',
    'nicaragua',
    'niger',
    'nigeria',
    'north macedonia',
    'norway',
    'oman',
    'pakistan',
    'panama',
    'papua new guinea',
    'paraguay',
    'peru',
    'philippines',
    'poland',
    'portugal',
    'qatar',
    'romania',
    'russia',
    'rwanda',
    'saint lucia',
    'saint vincent and the grenadines',
    'san marino',
    'saudi arabia',
    'senegal',
    'serbia',
    'seychelles',
    'singapore',
    'slovakia',
    'slovenia',
    'somalia',
    'south africa',
    'spain',
    'sri lanka',
    'sudan',
    'suriname',
    'sweden',
    'switzerland',
    'taiwan',
    'tanzania',
    'thailand',
    'togo',
    'trinidad and tobago',
    'tunisia',
    'turkey',
    'uganda',
    'ukraine',
    'united arab emirates',
    'united kingdom',
    'uruguay',
    'us',
    'uzbekistan',
    'venezuela',
    'vietnam',
    'zambia',
    'zimbabwe',
    'dominica',
    'grenada',
    'mozambique',
    'syria',
    'timor-leste',
    'belize'
]

#-----------------------------------------------------------------------

"""
Proportion by country. Data from CSSEGISandData/COVID-19.
"""
proportion = [
    6.058770069675856e-05,
    0.00024235080278703423,
    0.0010299909118448955,
    6.058770069675856e-05,
    0.0,
    0.0,
    0.00024235080278703423,
    0.0,
    0.0004241139048773099,
    0.0012723417146319298,
    6.058770069675856e-05,
    0.0,
    0.00012117540139351712,
    0.00018176310209027567,
    0.0,
    0.0,
    0.0053317176613147535,
    0.0,
    0.0,
    0.0,
    6.058770069675856e-05,
    0.002059981823689791,
    0.0,
    0.00018176310209027567,
    0.00024235080278703423,
    0.0,
    0.0,
    0.0,
    0.001514692517418964,
    0.0,
    0.0,
    0.00012117540139351712,
    0.19836413208118753,
    0.00018176310209027567,
    6.058770069675856e-05,
    0.00012117540139351712,
    0.0,
    6.058770069675856e-05,
    0.00048470160557406846,
    6.058770069675856e-05,
    6.058770069675856e-05,
    6.058770069675856e-05,
    0.0014541048167222054,
    0.0,
    0.00018176310209027567,
    0.0010905786125416542,
    0.0011511663132384125,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    6.058770069675856e-05,
    0.052226598000605876,
    6.058770069675856e-05,
    6.058770069675856e-05,
    0.0,
    0.007452287185701303,
    0.00012117540139351712,
    0.0010299909118448955,
    6.058770069675856e-05,
    0.0,
    6.058770069675856e-05,
    0.0,
    0.0,
    0.0,
    0.0004241139048773099,
    6.058770069675856e-05,
    0.0006058770069675856,
    0.002968797334141169,
    0.1097849136625265,
    0.0013935171160254468,
    0.00036352620418055135,
    6.058770069675856e-05,
    0.36819145713420176,
    6.058770069675856e-05,
    0.0025446834292638595,
    0.0,
    0.0,
    0.0,
    0.0067252347773402,
    0.0,
    0.0,
    0.0,
    0.00024235080278703423,
    0.0,
    0.0,
    6.058770069675856e-05,
    0.00048470160557406846,
    0.0,
    0.0008482278097546198,
    0.0,
    0.0,
    0.0,
    0.00012117540139351712,
    0.00018176310209027567,
    6.058770069675856e-05,
    0.0,
    0.0,
    6.058770069675856e-05,
    0.00024235080278703423,
    0.0,
    0.0,
    0.012965767949106331,
    0.0,
    0.0,
    0.0,
    6.058770069675856e-05,
    0.00012117540139351712,
    0.0006058770069675856,
    0.0,
    0.00036352620418055135,
    0.00036352620418055135,
    0.0,
    6.058770069675856e-05,
    0.0003029385034837928,
    0.0019993941229930322,
    0.00048470160557406846,
    0.0013935171160254468,
    0.0,
    0.0004241139048773099,
    6.058770069675856e-05,
    0.0,
    0.0,
    0.0,
    0.0012117540139351712,
    0.0,
    0.0,
    0.00018176310209027567,
    0.0,
    0.00012117540139351712,
    0.0,
    0.00018176310209027567,
    0.0,
    0.0,
    0.14001817631020902,
    0.0,
    6.058770069675856e-05,
    0.0,
    0.001514692517418964,
    0.007270524083611027,
    0.00012117540139351712,
    0.0,
    6.058770069675856e-05,
    0.0,
    0.0,
    0.00018176310209027567,
    0.0022417449257800667,
    0.0,
    0.00018176310209027567,
    0.00012117540139351712,
    0.020357467434110876,
    0.0,
    0.033747349288094516,
    0.0,
    0.0,
    0.0,
    0.0,
    6.058770069675856e-05,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0
]
